

config_version = 14


[brightness]
enable_ddcutil = true

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000004" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 1492.0
    cy = 341.0
    output = "eDP-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        forecast_days = 6
        show_forecast = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1492.0
    cy = 50.000003814697266
    output = "eDP-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "clock"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 0.0
    box_width = 0.0
    cx = 1492.0
    cy = 164.0
    output = "eDP-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        stat = "cpu_usage"
        stat2 = "cpu_temp"

[hot_corners]
enabled = true

    [hot_corners.top_right]
    action = "launcher"

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-5", "lockscreen-login-box@DP-4", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-4"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-4"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-4".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1197.3333740234375
    output = "DP-5"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 800.00006103515625
    cy = 718.0
    output = "eDP-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
niri_overview_type_to_launch_enabled = true

    [shell.animation]
    speed = 2.2500000335276127

    [shell.panel]
    clipboard_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true

[theme]
builtin = "Tokyo-Night"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "kitty", "niri", "qt" ]

[wallpaper]
enabled = false

    [wallpaper.default]
    path = "/home/vboysepe/Pictures/bgnew.jpg"

    [wallpaper.last]
    path = "/home/vboysepe/Pictures/bgnew.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/vboysepe/Pictures/bgnew.jpg"

    [[wallpaper.favorite]]
    builtin_palette = "Tokyo-Night"
    palette_source = "builtin"
    path = "/home/vboysepe/Pictures/bgnew.jpg"
    theme_mode = "dark"

[widget.clock]
format = "%I:%M %p"
tooltip_format = "{:%H:%M\\n%m/%d/%Y}"
